### ISSUE TITLE
new-ui-basemaps branch: keeps adding a "dummy" plugin repository?

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-connect-plugin#14]
plugin: head from new-ui-basemaps branch
qgis: 2.18.9

```
Error reading repository: Boundless Plugin Repository
Error downloading http://dummyurl.com?qgis=2.18 - server replied: Bad Request
```

**Comment by gioman** [comment]
According to @alexbruy is somethig added long ago, but now in this branch does not seems to work as expected, especially because it interferes with normal use of the plugin.

**Comment by gioman** [comment]
@volaya @alexbruy maybe this has started only *after* having run some test in tester plugin because now for a completely clean setup I cannot replicate (while using the plugin as normal user, so not running tests in tester plugin).

**Comment by alexbruy** [comment]
As I said previously, this is related to the one test and does not happen in day-to-day usage.

**Comment by alexbruy** [comment]
should be "fixed"
