### ISSUE TITLE
new-ui-basemaps branch: several wordings in manual tests needs changes to reflect the new tabbed interface/searches

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-connect-plugin#15]
Subject should say it all. Now all results are in 1 list, where in previous versions we had pagination.

**Comment by gioman** [comment]
I don't thin there should e need to change tests (I just run them), seems only wording must change.

**Comment by alexbruy** [comment]
Closed as "won't fix" because UI is not final yet.
