### ISSUE TITLE
new-ui-basemaps branch: icons too big in results in Windows, links not rendering as supposed

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-connect-plugin#17]
This is testing *before* the development is ended, nevertheless it can be useful if this is about something that can have been overlooked. In case just close.

Windows:
![screenshot_20170616_194932](https://user-images.githubusercontent.com/1951107/27240658-92e22782-52cd-11e7-8a37-9ad400a6620d.png)

Linux:

![screenshot_20170616_195208](https://user-images.githubusercontent.com/1951107/27240660-942e1e98-52cd-11e7-992a-de1d35b4599a.png)

**Comment by gioman** [comment]
Windows links:

![screenshot_20170616_195454](https://user-images.githubusercontent.com/1951107/27240694-b1111e70-52cd-11e7-9952-f75455bc07e3.png)

**Comment by volaya** [comment]
I can confirm that icons are huge in windows. I will work on fixing it

**Comment by volaya** [comment]
it's not really the icons, it looks like the css is not being used at all

**Comment by gioman** [comment]
> it's not really the icons, it looks like the css is not being used at all

this explains also the links not rendered correctly.

**Comment by gioman** [comment]
@volaya @alexbruy now is ok under windows both for knowlesdge and plugins tabs, but data one seems not ok (not even under Linux), see

![screenshot_20170619_135755](https://user-images.githubusercontent.com/1951107/27286283-72bc5b22-54f7-11e7-9599-6f8e2a362941.png)
