### ISSUE TITLE
Selecting any other knowledge category should remove the All category

### ISSUE THREAD

**Issue by SrNetoChan** [boundlessgeo/qgis-connect-plugin#21]
By default, only the `All` Category is selected under the Knowledge tab. When the user clicks/selects one or more of the other categories, the `All` Category should be automatically removed. otherwise the serach results will always be the same.

On the other hand, selecting `All` should remove any of the other categories.

**Comment by alexbruy** [comment]
This is not possible with current UI

**Comment by volaya** [comment]
When no category is selected, it searches for all. Maybe we can remove the "all" option, so the combo acts as a filter, and if nothing is selected, it doesnt filter at all

It looks like better UI to me

what do you think, @aneto, @alexbruy ?

**Comment by SrNetoChan** [comment]
I agree. It would be more intuitive to me. Not sure if Alison has a different idea tho.

**Comment by alexbruy** [comment]
"All" category removed
