### ISSUE TITLE
There's a mixed use for the tags/action buttons in results

### ISSUE THREAD

**Issue by SrNetoChan** [boundlessgeo/qgis-connect-plugin#22]
In the Plugins and Data tab, the blue buttons in results are exclusively actions "Install", "Add to map", etc... But in the knowledge tab they are also used for defining the category without making clear that you can click on them to trigger an action.

IMHO, these "buttons" should be renamed.

Documentation --> Go to documentation
Q&A --> Go to Q&A
Learning --> Go to Learning
Lesson --> Install lesson

**Comment by alexbruy** [comment]
This is excatly what was requested and completely identical to the approved mockups.
