### ISSUE TITLE
on macOS the "add to default project" option in data search results do not automatically activate the "create new project from default project" in QGIS options

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-connect-plugin#31]
It can be enabled manually, after that the default project works (meaning that it opens with the added default basemaps).

**Comment by gioman** [comment]
on Windows works as expected.

**Comment by gioman** [comment]
Ah sorry, this is on BD 1.1 with Connect shipped with it.

**Comment by alexbruy** [comment]
Can you try with `fix-settings` branch?

**Comment by gioman** [comment]
@alexbruy will do!

**Comment by gioman** [comment]
@alexbruy I tested it and from what I see there are no changes in macOS regarding this issue.

**Comment by alexbruy** [comment]
Just to clarify. You have no default project enabled, click on "add to default project" and default project created but corresponding setting in QGIS options not activated. This happens only on Mac, and works on other systems. Correct?

**Comment by alexbruy** [comment]
Fixed in master
