### ISSUE TITLE
Warn users when logging in without credential or wrong credential

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-connect-plugin#7]
It seems that when logging in with no credentials or *wrong* credentials that the user is always logged in with a "open" subscription, but no warning or message is returned in such cases, and this leave the user guessing why (it is not usual to log in somewhere with no credentials or wrongs ones).

**Comment by volaya** [comment]
@gioman what do you suggest doing?

we can show another message box, but that's not a nice UI/UX...

I was showing a text before "logged as: not logged" at the bottom of the panel, but Liz thought it would be better to just hide the login label...

**Comment by alexbruy** [comment]
For me attempt to log in with invalid credentials shows a warning message.

**Comment by gioman** [comment]
@volaya @alexbruy I think that a message saying something along the lines "No credentials or wrong credentials, Login to open subscription tier has been made" would help understand why the login has been made anyway.

**Comment by gioman** [comment]
@volaya @alexbruy or show the tier name somwhere

**Comment by volaya** [comment]
what do you think of this?

https://github.com/boundlessgeo/qgis-connect-plugin/commit/fe20056176297815debcfe8eeb75f7a0d4a57ebe

**Comment by gioman** [comment]
@volaya seems ok to me.

**Comment by gioman** [comment]
@volaya I guess this can be closed, right?

**Comment by alexbruy** [comment]
Seems we can close it now. Reopen if necessary
